name: Run Selenium Chrome automation and generate Extent report
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      #- run: |
          # echo "Installing Selenium WebDriver"
          # sudo apt-get install selenium-server-standalone
          #echo "Installing ChromeDriver"
          #wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          #unzip chromedriver_linux64.zip
          #sudo mv chromedriver /usr/local/bin/chromedriver
      #- run: |
          #echo "Running Selenium Chrome automation"
          #java -cp selenium-server-standalone-3.141.59.jar:. SeleniumChromeAutomation
      #- run: |
          #echo "Generating Extent report"
          #java -cp selenium-server-standalone-3.141.59.jar:. ExtentReportExample
      - name: Build with Maven
      - run: mvn -B package --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6          
