name: Run Selenium Chrome automation and generate Extent report
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: |
             sudo apt install google-chrome-stable
      - run: mvn -B package --file pom.xml
      #- run: |
      #    mvn surefire-report:report
      - uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: target/surefire-reports      
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'index.html'
      - uses: Sibz/github-status-action@v1
        with: 
            authToken: ${{secrets.GITHUB_TOKEN}}
            context: 'Test report'
            publish_dir: target
            target_url: leyongudinho.github.io/GitActionTest/${{ github.run_number }}          
