name: Run Selenium Chrome automation and generate Extent report
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: sudo curl -sS -o – https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
             sudo bash -c “echo ‘deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main’ >> /etc/apt/sources.list.d/google-chrome.list”
             sudo apt-get update
             sudo apt-get install google-chrome-stable     
      - run: mvn -B package --file pom.xml
